[project]
name = "shell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "pydantic>=2.10.4",
    "rich>=13.9.4",
    "textual-dev>=1.7.0",
    "textual>=1.0.0",
]
